Cleanup

diff --git a/run/checkvpshealth b/run/checkvpshealth
--- a/run/checkvpshealth
+++ b/run/checkvpshealth
@@ -378,25 +378,26 @@ if /usr/bin/ls /opt/rink/conf/drives/*."${vuser}".drive > /dev/null 2>&1; then
         unhealthy="true"
       else
         /usr/bin/ssh -o StrictHostKeyChecking=no -o ConnectTimeout=3 -T ${DriveVerber} -p ${VerbPort} -i /root/.ssh/${SSHKey} > /dev/null 2>&1 <<EOS
-if [ ! -e "/dev/${DriveDev}" ]; then /usr/bin/echo "Device for ${DriveNickName} not found."; exit 6; fi
-if [ ! -f "/opt/verb/conf/inkdrive/${DriveType}.${DriveName}" ]; then /usr/bin/echo "Config for ${DriveNickName} not found."; exit 6; fi
-/usr/bin/grep -q "^Device=${DriveDev}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || /usr/bin/echo "Drive device for ${DriveNickName} incorrect."; exit 6
-/usr/bin/grep -q "^Mount=${DriveName}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || /usr/bin/echo "Drive mount name for ${DriveNickName} incorrect."; exit 6
-/usr/bin/grep -q "^Type=${DriveType}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || /usr/bin/echo "Drive type for ${DriveNickName} incorrect."; exit 6
-/usr/bin/grep -q "^/dev/${DriveDev}1" /etc/fstab | grep -q "/mnt/${DriveName}" || /usr/bin/echo "Device for ${DriveNickName} not mounted."; exit 6
+if [ ! -e "/dev/${DriveDev}" ]; then exit 6; fi
+if [ ! -f "/opt/verb/conf/inkdrive/${DriveType}.${DriveName}" ]; then exit 6; fi
+/usr/bin/grep -q "^Device=${DriveDev}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || exit 6
+/usr/bin/grep -q "^Mount=${DriveName}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || exit 6
+/usr/bin/grep -q "^Type=${DriveType}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || exit 6
+/usr/bin/grep "^/dev/${DriveDev}1" /etc/fstab | grep -q "/mnt/${DriveName}" || exit 6
 EOS
         if [ "$?" != "0" ]; then
           /usr/bin/echo "Drive '${DriveNickName}' not connected correctly."
           unhealthy="true"
+          /usr/bin/echo "Check details with:"
           /usr/bin/cat <<EOS
-Check with:
-if [ ! -e "/dev/${DriveDev}" ]; then /usr/bin/echo "Device for ${DriveNickName} not found."; exit 6; fi
-if [ ! -f "/opt/verb/conf/inkdrive/${DriveType}.${DriveName}" ]; then /usr/bin/echo "Config for ${DriveNickName} not found."; exit 6; fi
-/usr/bin/grep -q "^Device=${DriveDev}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || /usr/bin/echo "Drive device for ${DriveNickName} incorrect."; exit 6
-/usr/bin/grep -q "^Mount=${DriveName}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || /usr/bin/echo "Drive mount name for ${DriveNickName} incorrect."; exit 6
-/usr/bin/grep -q "^Type=${DriveType}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || /usr/bin/echo "Drive type for ${DriveNickName} incorrect."; exit 6
-/usr/bin/grep -q "^/dev/${DriveDev}1" /etc/fstab | grep -q "/mnt/${DriveName}" || /usr/bin/echo "Device for ${DriveNickName} not mounted."; exit 6
-###
+ssh -o StrictHostKeyChecking=yes -o ConnectTimeout=3 ${namespace}.${VerbTLD} -p ${VerbPort} -i /root/.ssh/${SSHKey}
+if [ ! -e "/dev/${DriveDev}" ]; then echo fail; fi
+if [ ! -f "/opt/verb/conf/inkdrive/${DriveType}.${DriveName}" ]; then echo fail; fi
+grep -q "^Device=${DriveDev}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || echo fail
+grep -q "^Mount=${DriveName}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || echo fail
+grep -q "^Type=${DriveType}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || echo fail
+grep "^/dev/${DriveDev}1" /etc/fstab | grep -q "/mnt/${DriveName}" || echo fail
+### Done line by line, any error will output "fail"
 EOS
         fi
       fi
