Cleanup

diff --git a/run/checkvpshealth b/run/checkvpshealth
--- a/run/checkvpshealth
+++ b/run/checkvpshealth
@@ -15,7 +15,7 @@
 
 
 if [ -z "$3" ]; then
-  /usr/bin/echo "Needs namespace, TLD, user plan, region, & snapshot arguments, I quit."
+  /usr/bin/echo "Needs namespace, TLD & user arguments, I quit."
   exit 0
 fi
 
@@ -27,24 +27,34 @@ checkVerbTLD="$2"
 vuser="$3"
 
 # Check the existence of the verber
-if [ ! -f "/opt/rink/conf/${namespace}.${checkVerbTLD}.raw" ]; then
-  /usr/bin/echo "No raw conf file exists. Verber does not exist."
-  exit 0
+if [ ! -f "/opt/rink/conf/${namespace}.${checkVerbTLD}.raw" ] && [ ! -f "/opt/rink/conf/${namespace}.${checkVerbTLD}.vrb" ]; then
+  /usr/bin/echo "No config files exist. Nothing to check."
+  exit 8
+elif [ ! -f "/opt/rink/conf/${namespace}.${checkVerbTLD}.raw" ]; then
+  /usr/bin/echo "No .raw file exists."
+  /usr/bin/echo "Verber is not healthy!"
+  exit 6
+elif [ ! -f "/opt/rink/conf/${namespace}.${checkVerbTLD}.vrb" ]; then
+  /usr/bin/echo "No .vrb file exists."
+  /usr/bin/echo "Verber is not healthy!"
+  exit 6
 fi
 
-# Get the instance ID
-if [ -f "/opt/rink/conf/${namespace}.${checkVerbTLD}.vrb" ]; then
-  /usr/bin/echo ".vrb file found..."
+# Verify the instance ID and that the files in deed exist
+if [ -f "/opt/rink/conf/${namespace}.${checkVerbTLD}.vrb" ] && [ -f "/opt/rink/conf/${namespace}.${checkVerbTLD}.raw" ]; then
+  /usr/bin/echo "Config files found..."
   . /opt/rink/conf/${namespace}.${checkVerbTLD}.vrb
   . /opt/rink/ns/${VerbNameServersConfig}
   ## we can now use ${VultrInstanceID}
-  RawVultrInstanceID="$(/usr/bin/cat /opt/rink/conf/${namespace}.${checkVerbTLD}.raw | /usr/bin/grep ^ID | /usr/bin/sed s"/ID\t\t\t//")"
+  RawVultrInstanceID="$(/usr/bin/cat /opt/rink/conf/${namespace}.${VerbTLD}.raw | /usr/bin/grep ^ID | /usr/bin/sed s"/ID\t\t\t//")"
   if [ "${RawVultrInstanceID}" != "${VultrInstanceID}" ]; then
     /usr/bin/echo ".raw and .vrb conf files conflict."
-    unhealthy="true"
+    /usr/bin/echo "Verber is not healthy!"
+    exit 6
+  fi
 else
-  /usr/bin/echo "No .vrb file."
-  unhealthy="true"
+  /usr/bin/echo "Verber is not healthy!"
+  exit 6
 fi
 
 # Check conf credentials
@@ -74,6 +84,20 @@ rarpa_ipv6() {
   done
   printf 'ip6.arpa\n'
 }
+
+# Check VPS for responsiveness
+## Abbreviated waitvpson
+powerstatus="$(/usr/bin/vultr-cli instance get ${VultrInstanceID} | /usr/bin/grep '^POWER STATUS' | /usr/bin/sed s"/POWER STATUS\t\t//")"
+if [ "${powerstatus}" != "running" ]; then
+    /usr/bin/vultr-cli instance restart ${VultrInstanceID}
+    sleep 10
+fi
+## Check if responsive
+/opt/rink/run/waitvpsanswer ${namespace} ${VerbTLD} poweronce
+if [ "$?" != "0" ]; then
+  /usr/bin/echo "Verber is not healthy!"
+  exit 6
+fi
 
 # Conf file and settings
 /usr/bin/echo "Config settings"
@@ -109,7 +133,7 @@ else
     /usr/bin/echo "No valid IP to access Verber."
     unhealthy="true"
   fi
-  if [ "${checkHost}" != "${VerbHostID}.${namespace}.verb.${checkVerbTLD}" ]; then
+  if [ "${checkHost}" != "${VerbHostID}.${namespace}.verb.${VerbTLD}" ]; then
     . /opt/rink/inkdnsnameservers
     if [ "${checkHost}" = "${DefaultNS1}" ] && [ "${NameserverNS1IPv4}" = "${VerbIPv4}" ] && ( [ "${NameserverNS1IPv6}" = "${VerbIPv6}" ] || [ "${NameserverNS1IPv6}" = "${VerbIPv6Exp}" ] ); then
       /usr/bin/echo "Nameserver: ${checkHost}"
@@ -134,7 +158,7 @@ if [ -z "${VerbTLD}" ]; then
   /usr/bin/echo "VerbTLD missing from conf."
   unhealthy="true"
 else
-  if [ "${VerbTLD}" != "${checkVerbTLD}" ]; then
+  if [ "${VerbTLD}" != "${VerbTLD}" ]; then
     /usr/bin/echo "User doesn't match."
     unhealthy="true"
   fi
@@ -229,7 +253,7 @@ else
     unhealthy="true"
   else
     if ! /opt/rink/run/sshrun ${namespace} ${VerbTLD} ${vuser} "exit 0"; then
-      /usr/bin/echo "Verber can't be accessed."
+      /usr/bin/echo "Verber can't be accessed by normal means."
       unhealthy="true"
     fi
   fi
@@ -243,12 +267,12 @@ fi
 
 # Check nameservers
 /usr/bin/echo "Nameservers"
-if ! /usr/bin/ssh ${NS1Name}.${RinkVerbTLD} "exit 0"; then
-  /usr/bin/echo "Can't connect to ${NS1Host}."
+if ! /usr/bin/ssh -T -o StrictHostKeyChecking=yes root@${VerbIPv6} -p ${VerbPort} "/usr/bin/ssh ns1 'exit 0'"; then
+  /usr/bin/echo "It can't connect to ${NS1Host}."
   unhealthy="true"
 fi
-if ! /usr/bin/ssh ${NS2Name}.${RinkVerbTLD} "exit 0"; then
-  /usr/bin/echo "Can't connect to ${NS2Host}."
+if ! /usr/bin/ssh -T -o StrictHostKeyChecking=yes root@${VerbIPv6} -p ${VerbPort} "/usr/bin/ssh ns2 'exit 0'"; then
+  /usr/bin/echo "It can't connect to ${NS2Host}."
   unhealthy="true"
 fi
 if ! /usr/bin/ssh ${NS1Name}.${RinkVerbTLD} "/usr/bin/ls /srv/sns/${namespace}-${VerbTLD}"; then
@@ -260,7 +284,7 @@ if ! /usr/bin/ssh ${NS2Name}.${RinkVerbTLD} "/usr/bin/ls /srv/sns/${namespace}-$
   unhealthy="true"
 fi
 
-## Check ssh
+## Check ssh configs
 /usr/bin/echo "SSH config"
 if ! /usr/bin/grep -q "${IPv4}" /root/.ssh/known_hosts; then
   /usr/bin/echo "IPv4 not a known host."
@@ -269,7 +293,6 @@ fi
 if ! /usr/bin/grep -q "${IPv6Cmp}" /root/.ssh/known_hosts && ! /usr/bin/grep -q "${IPv6Exp}" /root/.ssh/known_hosts; then
   /usr/bin/echo "IPv6 not a known host."
   unhealthy="true"
-
 fi
 if ! /usr/bin/grep -q "Include" /root/.ssh/config | /usr/bin/grep -q "${namespace}.${VerbTLD}.ssh"; then
   /usr/bin/echo "SSH config not listed."
@@ -288,7 +311,11 @@ fi
 /usr/bin/grep -q '^ServerARPAIPv4="${VerbARPAIPv4}"' /opt/verb/conf/servernameip || exit 6
 /usr/bin/grep -q '^ServerARPAIPv6="${VerbARPAIPv6}"' /opt/verb/conf/servernameip || exit 6
 /usr/bin/grep -q '^ServerNS1DNS="${NS1Host}.${RinkDomain}"' /opt/verb/conf/servernameip || exit 6
+/usr/bin/grep -q '^ServerNS1IPv4="${NS1IPv4}"' /opt/verb/conf/servernameip || exit 6
+/usr/bin/grep -q '^ServerNS1IPv6="${NS1IPv6}"' /opt/verb/conf/servernameip || exit 6
 /usr/bin/grep -q '^ServerNS2DNS="${NA2Host}.${RinkDomain}"' /opt/verb/conf/servernameip || exit 6
+/usr/bin/grep -q '^ServerNS2IPv4="${NS2IPv4}"' /opt/verb/conf/servernameip || exit 6
+/usr/bin/grep -q '^ServerNS2IPv6="${NS2IPv6}"' /opt/verb/conf/servernameip || exit 6
 /usr/bin/grep -q '^127.0.1.1 ${VerbHostID}.${namespace}.verb.${VerbTLD} ${VerbHostID}' /opt/verb/conf/servernameip || exit 6
 /usr/bin/grep -q '^${VerbIPv4} ${VerbHostID}.${namespace}.verb.${VerbTLD} ${VerbHostID}' /opt/verb/conf/servernameip || exit 6
 /usr/bin/grep -q '^${VerbIPv6} ${VerbHostID}.${namespace}.verb.${VerbTLD} ${VerbHostID}' /etc/hosts || /usr/bin/grep -q '^${VerbIPv6Exp} ${VerbHostID}.${namespace}.verb.${VerbTLD} ${VerbHostID}' /etc/hosts || exit 6
diff --git a/run/purgevps b/run/purgevps
--- a/run/purgevps
+++ b/run/purgevps
@@ -15,7 +15,7 @@
 
 
 if [ -z "$3" ]; then
-  /usr/bin/echo "Needs namespace, TLD, user plan, region, & snapshot arguments, I quit."
+  /usr/bin/echo "Needs namespace, TLD & user arguments, I quit."
   exit 0
 fi
 
@@ -29,8 +29,8 @@ vuser="$3"
 
 # Check the existence of the verber
 if [ ! -f "/opt/rink/conf/${namespace}.${VerbTLD}.raw" ]; then
-  /usr/bin/echo "No raw conf file exists. Checking for drives..."
-  if [ -n "$(/usr/bin/ls /opt/rink/drive/*."${vuser}".drive)" ]; then
+  /usr/bin/echo "No raw conf file exists. Checking for orphaned drives..."
+  if [ ! -f "/opt/rink/conf/${namespace}.${VerbTLD}.vrb" ] && [ -n "$(/usr/bin/ls /opt/rink/drive/*."${vuser}".drive)" ]; then
     # put each listed drive's config file (with absolute path) in an array so we can loop through and check each
     driveConfigs=($(/usr/bin/grep -HRl "${namespace}.${VerbTLD}" /opt/rink/drive/*."${vuser}".drive))
     # the variable form ${#driveConfigs[@]} shows how many items in the $driveConfigs array
@@ -44,15 +44,25 @@ if [ ! -f "/opt/rink/conf/${namespace}.${VerbTLD}.raw" ]; then
     if [ "${#driveConfigs[@]}" -gt "0" ]; then
       for drive in ${driveConfigs}; do
         . ${drive}
-        /opt/rink/run/unplugdrive ${namespace} ${VerbTLD} ${vuser} ${drive}
-        /opt/rink/run/killdrive ${vuser} ${drive}
+        /opt/rink/run/unplugdrive ${namespace} ${VerbTLD} ${vuser} ${DriveNickName}
+        /opt/rink/run/killdrive ${vuser} ${DriveNickName}
       done
     fi
+  elif [ ! -f "/opt/rink/conf/${namespace}.${VerbTLD}.vrb" ]; then
+    /usr/bin/echo "No orphaned drives for user. Nothing to do here."
+    exit 0
   else
-    /usr/bin/echo "No drives for user"
+    /usr/bin/echo "Other configs exist, checking integrity..."
+  fi
+elif [ -f "/opt/rink/conf/${namespace}.${VerbTLD}.vrb" ]; then
+  /usr/bin/echo "Configs exist, checking integrity..."
+  /opt/rink/run/checkvpshealth ${namespace} ${VerbTLD} ${vuser}
+  if [ "$?" = "0" ]; then
+    /usr/bin/echo "Verber checks out healthy. Cannot purge!"
+    exit 4
   fi
 else
-  /usr/bin/echo ".raw file found..."
+  /usr/bin/echo "Only .raw config file found..."
 fi
 
 # Get some basic information
diff --git a/run/waitvpsanswer b/run/waitvpsanswer
--- a/run/waitvpsanswer
+++ b/run/waitvpsanswer
@@ -5,10 +5,11 @@
 ## This script will loop until finished, whether ssh keys are either accepted or rejected, so long as the server is up and responsive
 
 # How to use:
-## ./waitvpsanswer [verb-namespace] [tld]
+## ./waitvpsanswer [verb-namespace] [tld] [poweronce - optional to only run power cycle once]
 
 # Eg:
 ## ./waitvpsanswer name ink
+## ./waitvpsanswer name ink poweronce
 
 
 if [ -z "$2" ]; then
@@ -18,6 +19,10 @@ fi
 
 namespace="$1"
 VerbTLD="$2"
+
+if [ -n "$3" ] && [ "$3" = "poweronce" ]; then
+  poweronce="true"
+fi
 
 if [ ! -f "/opt/rink/conf/${namespace}.${VerbTLD}.vrb" ]; then
   /usr/bin/echo "${namespace}.${VerbTLD} does not exist! I quit."
@@ -78,10 +83,21 @@ if [ "${isIP4}" = "true" ]; then
   fi
     /usr/bin/grep -q 'key' /opt/rink/tmp/waiton.${namespace}.${VerbTLD}
     greptest="$?"
+    ### If a fast test, fail after a short time
+    if [ -n "${poweronce}" ] && [ "${poweronce}" = "true" ]; then
+        if [ "$count" -gt "7" ]; then
+          fail="true"
+          break
+        elif [ "$count" -gt "5" ]; then
+          /opt/rink/run/powercycle ${namespace} ${VerbTLD}
+          sleep 15
+        fi
     ### If we have been trying 10 minutes, restart
-    if [ "$count" -gt "60" ]; then
-      /opt/rink/run/powercycle ${namespace} ${VerbTLD}
-      count=0
+    else 
+      if [ "$count" -gt "60" ]; then
+        /opt/rink/run/powercycle ${namespace} ${VerbTLD}
+        count=0
+      fi
     fi
     ((count++))
   done
@@ -111,13 +127,30 @@ if [ "${isIP6}" = "true" ]; then
     ### Keep checking the IPv6 (because it keeps changing in spinup)
     IPv6="$(/usr/bin/vultr-cli instance ipv6 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
     sshCall="root@${IPv6} -p ${VerbPort} -i /root/.ssh/${SSHKey}"
+        ### If a fast test, fail after a short time
+    if [ -n "${poweronce}" ] && [ "${poweronce}" = "true" ]; then
+        if [ "$count" -gt "7" ]; then
+          fail="true"
+          break
+        elif [ "$count" -gt "5" ]; then
+          /opt/rink/run/powercycle ${namespace} ${VerbTLD}
+          sleep 15
+        fi
     ### If we have been trying 10 minutes, restart
-    if [ "$count" -gt "60" ]; then
-      /opt/rink/run/powercycle ${namespace} ${VerbTLD}
-      count=0
+    else
+      if [ "$count" -gt "60" ]; then
+        /opt/rink/run/powercycle ${namespace} ${VerbTLD}
+        count=0
+      fi
     fi
     ((count++))
   done
   ## Cleanup
   /usr/bin/rm -f /opt/rink/tmp/waiton.${namespace}.${VerbTLD}
+fi
+
+# Poweronce test?
+if [ -n "${poweronce}" ] && [ "${poweronce}" = "true" ] && [ "${fail}" = "true" ]; then
+  /usr/bin/echo "Verber is NR."
+  exit 6
 fi
