Production ready

diff --git a/run/importvps b/run/importvps
--- a/run/importvps
+++ b/run/importvps
@@ -44,18 +44,19 @@ elif [ "${VerbTLD}" != "${RinkVerbTLD}'" ] && [ -f "/opt/rink/conf/vrb.${namespa
   fi
 fi
 
+#NOTE We don't get the last Verb ID because we use the host already on the imported verber
 # Get the latest Verb ID number
-if [ -f "/opt/rink/lastverbid" ]; then
-  . /opt/rink/lastverbid
-  HostID=$(( LASTID + 1 ))
-else
-  HostID="1"
-fi
-## Make sure it is not in use
-### grep "-s, --no-messages suppress error messages"
-while /usr/bin/grep -qs ^VerbHostID=\"$HostID\" /opt/rink/conf/vrb.* > /dev/null; do
-  HostID=$(( HostID + 1 ))
-done
+# if [ -f "/opt/rink/lastverbid" ]; then
+#   . /opt/rink/lastverbid
+#   HostID=$(( LASTID + 1 ))
+# else
+#   HostID="1"
+# fi
+# ## Make sure it is not in use
+# ### grep "-s, --no-messages suppress error messages"
+# while /usr/bin/grep -qs ^VerbHostID=\"$HostID\" /opt/rink/conf/vrb.* > /dev/null; do
+#   HostID=$(( HostID + 1 ))
+# done
 
 # Check if the VPS ID even exists
 if ! /usr/bin/vultr-cli instance list | /usr/bin/grep -q "^${VultrInstanceID}"; then
@@ -94,6 +95,17 @@ fi
 VultrRegion="$(/usr/bin/vultr-cli instance get "${VultrInstanceID}" | /usr/bin/grep REGION | /usr/bin/sed -r 's/REGION\s+//')"
 IPv4="$(/usr/bin/vultr-cli instance ipv4 list $VultrInstanceID | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
 IPv6="$(/usr/bin/vultr-cli instance ipv6 list $VultrInstanceID | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
+
+# Get the Host
+/usr/bin/ssh ${namespace}.${VerbTLD} /usr/bin/cat /opt/verb/conf/servernameip > /opt/rink/tmp/servernameip.${namespace}.${VerbTLD}
+. /opt/rink/tmp/servernameip.${namespace}.${VerbTLD}
+## Validate
+if [ -z "${ServerHost}" ] || [ "${ServerName}" != "${namespace}" ] || [ "${ServerTLD}" != "${VerbTLD}" ]; then
+  /usr/bin/echo "Imported verber not properly configured, cannot proceed!"
+  exit 8
+else
+  HostID="$ServerHost"
+fi
 
 # IP addresses
 /usr/bin/echo "IPv4: $IPv4"
@@ -188,6 +200,20 @@ IPv6Exp=$(expand_ipv6 ${IPv6})
 IPv4ARPA=$(/bin/echo ${IPv4} | sed -r 's/^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$/\4.\3.\2.\1.in-addr.arpa/')
 IPv6ARPA=$(rarpa_ipv6 ${IPv6Exp})
 
+# Validate IP addresses
+if [ "${ServerExpIPv6}" != "${IPv6Exp}" ] && [ "${ServerExpIPv6}" != "NOIP6" ]; then
+  /usr/bin/echo "IPv6 addresses for imported verber do not agree, cannot proceed!
+Server reports: ${IPv6Exp}
+Verber records: ${ServerExpIPv6}"
+  exit 8
+fi
+if [ "${ServerIPv4}" != "${IPv4}" ] && [ "${ServerIPv4}" != "NOIP4" ]; then
+  /usr/bin/echo "IPv4 addresses for imported verber do not agree, cannot proceed!
+Server reports: ${IPv4}
+Verber records: ${ServerIPv4}"
+  exit 8
+fi
+
 /usr/bin/cat <<EOF > /opt/rink/conf/vrb.${namespace}.${VerbTLD}.conf
 VultrInstanceID="${VultrInstanceID}"
 VerbHostID="${HostID}"
@@ -268,9 +294,6 @@ elif [ "${ns2already}" = "true" ]; then
   /usr/bin/echo "SNS user already exists on nameserver ${NS2Host}. Fix that first."
   exit 7
 fi
-
-# Last ID (Only when we got this far)
-/usr/bin/echo "LASTID=\"$HostID\"" > /opt/rink/lastverbid
 
 # Update the NS information on the imported verber
 /usr/bin/ssh ${namespace}.${VerbTLD} "/opt/verb/serfs/updateverber"
