Production ready

diff --git a/run/importvps b/run/importvps
--- a/run/importvps
+++ b/run/importvps
@@ -23,22 +23,22 @@ fi
 # Defaults
 . /opt/rink/rinknames
 
-NAMESPACE="$1"
+namespace="$1"
 VerbTLD="$2"
-USER="$3"
+vuser="$3"
 VultrInstanceID="$4"
 
 # Check to see if this verber already exists by this name
-if [ -f /opt/rink/conf/vrb.${NAMESPACE}.${VerbTLD}.conf ]; then
-  /usr/bin/echo "Verber with name '${VerbTLD}' and TLD '${NAMESPACE}' already exists."
+if [ -f /opt/rink/conf/vrb.${namespace}.${VerbTLD}.conf ]; then
+  /usr/bin/echo "Verber with name '${VerbTLD}' and TLD '${namespace}' already exists."
   exit 5
-elif [ "${VerbTLD}" != "ink" ] && [ ! -f "/opt/rink/conf/vrb.${NAMESPACE}.ink.conf" ]; then
-  /usr/bin/echo "Verber with 'ink' TLD must be created for '${NAMESPACE}' before creating non-'ink' TLD verbers."
+elif [ "${VerbTLD}" != "ink" ] && [ ! -f "/opt/rink/conf/vrb.${namespace}.ink.conf" ]; then
+  /usr/bin/echo "Verber with 'ink' TLD must be created for '${namespace}' before creating non-'ink' TLD verbers."
   exit 5
-elif [ "${VerbTLD}" != "ink" ] && [ -f "/opt/rink/conf/vrb.${NAMESPACE}.ink.conf" ]; then
-  . /opt/rink/conf/vrb.${NAMESPACE}.ink.conf
-  if [ "${VerbUser}" != "${USER}" ]; then
-    /usr/bin/echo "Verb name '${NAMESPACE}' is already owned by another user."
+elif [ "${VerbTLD}" != "ink" ] && [ -f "/opt/rink/conf/vrb.${namespace}.ink.conf" ]; then
+  . /opt/rink/conf/vrb.${namespace}.ink.conf
+  if [ "${VerbUser}" != "${vuser}" ]; then
+    /usr/bin/echo "Verb name '${namespace}' is already owned by another user."
     exit 5
   fi
 fi
@@ -66,7 +66,7 @@ fi
 . /opt/rink/portnum
 
 # Create the instance
-/usr/bin/vultr-cli instance get "${VultrInstanceID}" > /opt/rink/conf/raw.${NAMESPACE}.${VerbTLD}.conf
+/usr/bin/vultr-cli instance get "${VultrInstanceID}" > /opt/rink/conf/raw.${namespace}.${VerbTLD}.conf
 
 # Exit status?
 e="$?"; if [ "$e" != "0" ]; then
@@ -75,17 +75,17 @@ e="$?"; if [ "$e" != "0" ]; then
 fi
 
 # Did it work?
-if [ -f /opt/rink/conf/raw.${NAMESPACE}.${VerbTLD}.conf ]; then
-  if ! /usr/bin/grep -q ^ID /opt/rink/conf/raw.${NAMESPACE}.${VerbTLD}.conf; then
+if [ -f /opt/rink/conf/raw.${namespace}.${VerbTLD}.conf ]; then
+  if ! /usr/bin/grep -q ^ID /opt/rink/conf/raw.${namespace}.${VerbTLD}.conf; then
     /usr/bin/echo "VPS output file is not correct, start over."
-    /usr/bin/rm -f "*.${NAMESPACE}.${VerbTLD}.conf"
-    /usr/bin/sed -i "/ssh.${NAMESPACE}.${VerbTLD}.conf/d" /root/.ssh/config
+    /usr/bin/rm -f "*.${namespace}.${VerbTLD}.conf"
+    /usr/bin/sed -i "/ssh.${namespace}.${VerbTLD}.conf/d" /root/.ssh/config
     exit 4
   fi
 else
   /usr/bin/echo "VPS output file does not exist, start over."
-  /usr/bin/rm -f "*.${NAMESPACE}.${VerbTLD}.conf"
-  /usr/bin/sed -i "/ssh.${NAMESPACE}.${VerbTLD}.conf/d" /root/.ssh/config
+  /usr/bin/rm -f "*.${namespace}.${VerbTLD}.conf"
+  /usr/bin/sed -i "/ssh.${namespace}.${VerbTLD}.conf/d" /root/.ssh/config
   exit 4
 fi
 
@@ -187,13 +187,13 @@ IP6EXP=$(expand_ipv6 ${IP6})
 IP4ARPA=$(/bin/echo ${IP4} | sed -r 's/^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$/\4.\3.\2.\1.in-addr.arpa/')
 IP6ARPA=$(rarpa_ipv6 ${IP6EXP})
 
-/usr/bin/cat <<EOF > /opt/rink/conf/vrb.${NAMESPACE}.${VerbTLD}.conf
+/usr/bin/cat <<EOF > /opt/rink/conf/vrb.${namespace}.${VerbTLD}.conf
 VultrInstanceID="${VultrInstanceID}"
 VerbHostID="${HOSTID}"
-VerbName="${NAMESPACE}"
+VerbName="${namespace}"
 VerbTLD="${VerbTLD}"
 VerbRegion="${VultrRegion}"
-VerbUser="${USER}"
+VerbUser="${vuser}"
 VerbPort="${Port}"
 VerbIPv4="${IP4}"
 VerbIPv6="${IP6NEW}"
@@ -204,9 +204,9 @@ EOF
 
 # Create the .ssh/config entry
 . /opt/rink/sshkey
-/usr/bin/echo "Include /opt/rink/conf/ssh.${NAMESPACE}.${VerbTLD}.conf" >> /root/.ssh/config
-/usr/bin/cat <<EOF > /opt/rink/conf/ssh.${NAMESPACE}.${VerbTLD}.conf
-Host ${NAMESPACE}.${VerbTLD}
+/usr/bin/echo "Include /opt/rink/conf/ssh.${namespace}.${VerbTLD}.conf" >> /root/.ssh/config
+/usr/bin/cat <<EOF > /opt/rink/conf/ssh.${namespace}.${VerbTLD}.conf
+Host ${namespace}.${VerbTLD}
 Hostname ${IP4}
 User root
 Port ${Port}
@@ -215,23 +215,30 @@ EOF
 
 # Wait for powerup
 /usr/bin/echo "Checking if VPS can be accessed..."
-/opt/rink/run/waitvpsanswer ${NAMESPACE} ${VerbTLD}
+/opt/rink/run/waitvpsanswer ${namespace} ${VerbTLD}
 e="$?"; if [ "$e" != "0" ]; then
   /usr/bin/echo "VPS cannot be accessed. It is possible that the keys are not installed. Make sure that they key '${SSHKey}' is properly installed on this VPS, then try again."
-  /usr/bin/rm -f "*.${NAMESPACE}.${VerbTLD}.conf"
+  /usr/bin/rm -f "*.${namespace}.${VerbTLD}.conf"
   exit "$e"
 fi
 
 # Refresh the SSHD keys on the server (they are still original from the snapshot and will seem like a duplicate in /root/.ssh/known_hosts)
 ## Do this in a loop
-/usr/bin/ssh -o StrictHostKeyChecking=no -o ConnectTimeout=3 -q ${NAMESPACE}.${VerbTLD} "/usr/bin/rm /etc/ssh/ssh_host_* && /usr/bin/ssh-keygen -A && /usr/bin/reboot"
-SSHRESETSTATUS="$?"
-while [ "$SSHRESETSTATUS" != "0" ]; do
-  /usr/bin/echo "newvps ssh-keygen loop reboot error: $SSHRESETSTATUS
+/usr/bin/ssh -o StrictHostKeyChecking=no -o ConnectTimeout=3 -q ${namespace}.${VerbTLD} "/usr/bin/rm /etc/ssh/ssh_host_* && /usr/bin/ssh-keygen -A && /usr/bin/reboot"
+sshresetstatus="$?"
+count=0
+while [ "$sshresetstatus" != "0" ]; do
+  /usr/bin/echo "newvps ssh-keygen loop reboot error: $sshresetstatus
   Waiting, then trying again..."
   sleep 3
-  /usr/bin/ssh -o StrictHostKeyChecking=no -o ConnectTimeout=3 -q ${NAMESPACE}.${VerbTLD} "/usr/bin/rm -f /etc/ssh/ssh_host_* && /usr/bin/ssh-keygen -A && /usr/bin/reboot"
-  SSHRESETSTATUS="$?"
+  /usr/bin/ssh -o StrictHostKeyChecking=no -o ConnectTimeout=3 -q ${namespace}.${VerbTLD} "/usr/bin/rm -f /etc/ssh/ssh_host_* && /usr/bin/ssh-keygen -A && /usr/bin/reboot"
+  sshresetstatus="$?"
+  # If we have been trying 10 minutes, restart
+  if [ "$count" -gt "200" ]; then
+    /opt/rink/run/powercycle ${namespace} ${VerbTLD}
+    count=0
+  fi
+  ((count++))
 done
 
 #DEV: probably replace the final `&& reboot` with a vultr-cli ...restart instance (however that works)
@@ -241,14 +248,14 @@ done
 
 # Add the hashed key
 sleep 10 # The server needs to start its reboot
-/opt/rink/run/waitvpson ${NAMESPACE} ${VerbTLD}
-/opt/rink/run/waitvpsanswer ${NAMESPACE} ${VerbTLD}
-/opt/rink/run/keyscan ${NAMESPACE} ${VerbTLD}
+/opt/rink/run/waitvpson ${namespace} ${VerbTLD}
+/opt/rink/run/waitvpsanswer ${namespace} ${VerbTLD}
+/opt/rink/run/keyscan ${namespace} ${VerbTLD}
 e="$?"; [[ "$e" = "0" ]] || exit "$e"
 
 # Check for existing sns user
-/usr/bin/ssh -q -o StrictHostKeyChecking=yes ${NS1Name}.${RinkVerbTLD} [[ -d "/srv/sns/${NAMESPACE}-${VerbTLD}" ]] && ns1already="true"
-/usr/bin/ssh -q -o StrictHostKeyChecking=yes ${NS2Name}.${RinkVerbTLD} [[ -d "/srv/sns/${NAMESPACE}-${VerbTLD}" ]] && ns2already="true"
+/usr/bin/ssh -q -o StrictHostKeyChecking=yes ${NS1Name}.${RinkVerbTLD} [[ -d "/srv/sns/${namespace}-${VerbTLD}" ]] && ns1already="true"
+/usr/bin/ssh -q -o StrictHostKeyChecking=yes ${NS2Name}.${RinkVerbTLD} [[ -d "/srv/sns/${namespace}-${VerbTLD}" ]] && ns2already="true"
 if [ "${ns1already}" = "true" ] && [ "${ns2already}" = "true" ]; then
   /usr/bin/echo "SNS user already exists on nameserver ${NS1Host} & ${NA2Host}. Fix that first."
   exit 7
@@ -264,26 +271,26 @@ fi
 /usr/bin/echo "LASTID=\"$HOSTID\"" > /opt/rink/lastverbid
 
 # Update the NS information on the imported verber
-/usr/bin/ssh ${NAMESPACE}.${VerbTLD} "/opt/verb/serfs/updateverber"
-/usr/bin/cat /opt/rink/inkdnsnameservers | /usr/bin/ssh ${NAMESPACE}.${VerbTLD} "/usr/bin/cat > /opt/verb/conf/inklists/inkdnsnameservers"
-/usr/bin/ssh ${NAMESPACE}.${VerbTLD} "/opt/verb/serfs/inkdnssetns1"
-/usr/bin/ssh ${NAMESPACE}.${VerbTLD} "/opt/verb/serfs/inkdnssetns2"
-/usr/bin/ssh ${NAMESPACE}.${VerbTLD} "/opt/verb/serfs/inkdnsrefreshbind"
+/usr/bin/ssh ${namespace}.${VerbTLD} "/opt/verb/serfs/updateverber"
+/usr/bin/cat /opt/rink/inkdnsnameservers | /usr/bin/ssh ${namespace}.${VerbTLD} "/usr/bin/cat > /opt/verb/conf/inklists/inkdnsnameservers"
+/usr/bin/ssh ${namespace}.${VerbTLD} "/opt/verb/serfs/inkdnssetns1"
+/usr/bin/ssh ${namespace}.${VerbTLD} "/opt/verb/serfs/inkdnssetns2"
+/usr/bin/ssh ${namespace}.${VerbTLD} "/opt/verb/serfs/inkdnsrefreshbind"
 
 # Rink user setup
 ## Make this Verber look like it is pre-setup
-/usr/bin/ssh ${NAMESPACE}.${VerbTLD} "/usr/bin/cp -f /opt/verb/conf/servertldstatus /opt/verb/conf/servertldstatus286"
-/usr/bin/ssh ${NAMESPACE}.${VerbTLD} "/usr/bin/cp -f /opt/verb/conf/servernameip /opt/verb/conf/servernameip286"
+/usr/bin/ssh ${namespace}.${VerbTLD} "/usr/bin/cp -f /opt/verb/conf/servertldstatus /opt/verb/conf/servertldstatus286"
+/usr/bin/ssh ${namespace}.${VerbTLD} "/usr/bin/cp -f /opt/verb/conf/servernameip /opt/verb/conf/servernameip286"
 ## Create the actual rink keys and users
 /opt/rink/run/newverbrinkkeys name ink start
 ## Restore this Verber for post-setop
-/usr/bin/ssh ${NAMESPACE}.${VerbTLD} "/usr/bin/sed -i '/RinkConfigured=.*/d' /opt/verb/conf/servernameip"
-/usr/bin/ssh ${NAMESPACE}.${VerbTLD} "/usr/bin/cat /opt/verb/conf/servernameip286 >> /opt/verb/conf/servernameip"
-/usr/bin/ssh ${NAMESPACE}.${VerbTLD} "/usr/bin/rm -f /opt/verb/conf/servernameip286"
-/usr/bin/ssh ${NAMESPACE}.${VerbTLD} "/usr/bin/rm -f /opt/verb/conf/servertldstatus286"
+/usr/bin/ssh ${namespace}.${VerbTLD} "/usr/bin/sed -i '/RinkConfigured=.*/d' /opt/verb/conf/servernameip"
+/usr/bin/ssh ${namespace}.${VerbTLD} "/usr/bin/cat /opt/verb/conf/servernameip286 >> /opt/verb/conf/servernameip"
+/usr/bin/ssh ${namespace}.${VerbTLD} "/usr/bin/rm -f /opt/verb/conf/servernameip286"
+/usr/bin/ssh ${namespace}.${VerbTLD} "/usr/bin/rm -f /opt/verb/conf/servertldstatus286"
 
 # Tell the Verber to import itself to the nameservers
-/usr/bin/ssh ${NAMESPACE}.${VerbTLD} "/opt/verb/serfs/rinkimportme"
+/usr/bin/ssh ${namespace}.${VerbTLD} "/opt/verb/serfs/rinkimportme"
 
 # Finish
-/usr/bin/echo "${NAMESPACE}.${VerbTLD} imported. It's identity key has changed, so you will need to remove lines with those IP addresses from any .ssh/known_hosts files on machines previously used to access it."
+/usr/bin/echo "${namespace}.${VerbTLD} imported. It's identity key has changed, so you will need to remove lines with those IP addresses from any .ssh/known_hosts files on machines previously used to access it."
