Troubleshooting

diff --git a/run/newvps b/run/newvps
--- a/run/newvps
+++ b/run/newvps
@@ -162,9 +162,20 @@ while [ "${IPv4nozero}" = "0.0.0.0" ] || [ "${IPv4nozero}" = "" ]; do
   ((faillimit++))
 done
 
-# Make sure IPv6 is valid
-#IPv6nozero="$(/usr/bin/vultr-cli instance ipv6 list ${VultrInstanceID} 2> /dev/null | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
-# SOME CODE HERE
+# Make sure IPv6 is not empty; wait until it has some value
+IPv6nozero="$(/usr/bin/vultr-cli instance ipv6 list ${VultrInstanceID} 2> /dev/null | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
+while [ "${IPv6nozero}" = "" ]; do
+  IPv6nozero="$(/usr/bin/vultr-cli instance ipv6 list ${VultrInstanceID} 2> /dev/null | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//' 2> /dev/null)"
+  /usr/bin/sleep 1
+  ### Fail proof
+  if [ "$faillimit" -gt "405" ]; then
+    /opt/rink/run/purgevps ${namespace} ${VerbTLD} ${vuser}
+    e="$?"; [[ "$e" = "0" ]] || exit "$e"
+    /usr/bin/echo "Awe, snap! Could not create ${namespace}.${VerbTLD} properly, likely due to brief backend down time. Try again now or within a few minutes."
+    exit 4
+  fi
+  ((faillimit++))
+done
 
 # Wait for IPv4 to populate (Default until set: 0.0.0.0)
 # firstIPv4PLACEHOLDER="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
@@ -307,21 +318,12 @@ fi
 # Process IPs to list for keyscan
 
 ## Finalize the IP addresses (because they keep changing in spinup)
-echo "vultr-cli instance ipv4 list ${VultrInstanceID}" #DEV
 IPv4="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} 2> /dev/null | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
-echo $IPv4 #DEV
-echo "vultr-cli instance ipv6 list ${VultrInstanceID}" #DEV
 IPv6Raw=$(/usr/bin/vultr-cli instance ipv6 list ${VultrInstanceID} 2> /dev/null | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')
-echo "IPv6: $IPv6Raw" #DEV
 IPv6Cmp=$(compress_ipv6 ${IPv6Raw})
-echo $IPv6Cmp #DEV
 IPv6Exp=$(expand_ipv6 ${IPv6Raw})
-echo $IPv6Exp #DEV
 IPv4ARPA=$(/usr/bin/echo ${IPv4} | /usr/bin/sed -r 's/^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$/\4.\3.\2.\1.in-addr.arpa/')
-echo $IPv4ARPA #DEV
 IPv6ARPA=$(rarpa_ipv6 ${IPv6Exp})
-echo $IPv6ARPA #DEV
-exit #DEV
 
 ## Remove the local server fingerfprint
 ### We have been approving into a new VPS with a stock host RSA key (on the snapshot); it needs to be removed from our local known_hosts check
