Troubleshooting

diff --git a/run/newvps b/run/newvps
--- a/run/newvps
+++ b/run/newvps
@@ -146,22 +146,6 @@ EOF
 /usr/bin/echo "New VPS instance ${namespace}.${VerbTLD} initiated. Waiting a few seconds for details to populate..."
 /usr/bin/sleep 5
 
-# Make sure that the IPv4 is not 0.0.0.0; wait until this is done right
-faillimit=0
-IPv4nozero="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//' 2> /dev/null)"
-while [ "${IPv4nozero}" = "0.0.0.0" ]; do
-  IPv4nozero="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//' 2> /dev/null)"
-  /usr/bin/sleep 1
-  ### Fail proof
-  if [ "$faillimit" -gt "405" ]; then
-    /opt/rink/run/purgevps ${namespace} ${VerbTLD} ${vuser}
-    e="$?"; [[ "$e" = "0" ]] || exit "$e"
-    /usr/bin/echo "Awe, snap! Could not create ${namespace}.${VerbTLD} properly, likely due to brief backend down time. Try again now or within a few minutes."
-    exit 4
-  fi
-  ((faillimit++))
-done
-
 # Wait for IPv4 to populate (Default until set: 0.0.0.0)
 # firstIPv4PLACEHOLDER="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
 # faillimit=0
@@ -301,6 +285,22 @@ if [ "$e" != "0" ]; then
   exit "$e"
 fi
 # Process IPs to list for keyscan
+
+# Make sure that the IPv4 is not 0.0.0.0; wait until this is done right
+faillimit=0
+IPv4nozero="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//' 2> /dev/null)"
+while [ "${IPv4nozero}" = "0.0.0.0" ]; do
+  IPv4nozero="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//' 2> /dev/null)"
+  /usr/bin/sleep 1
+  ### Fail proof
+  if [ "$faillimit" -gt "405" ]; then
+    /opt/rink/run/purgevps ${namespace} ${VerbTLD} ${vuser}
+    e="$?"; [[ "$e" = "0" ]] || exit "$e"
+    /usr/bin/echo "Awe, snap! Could not create ${namespace}.${VerbTLD} properly, likely due to brief backend down time. Try again now or within a few minutes."
+    exit 4
+  fi
+  ((faillimit++))
+done
 
 ## Finalize the IP addresses (because they keep changing in spinup)
 IPv4="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
