Troubleshooting

diff --git a/run/newvps b/run/newvps
--- a/run/newvps
+++ b/run/newvps
@@ -146,6 +146,22 @@ EOF
 /usr/bin/echo "New VPS instance ${namespace}.${VerbTLD} initiated. Waiting a few seconds for details to populate..."
 /usr/bin/sleep 5
 
+# Make sure that the IPv4 is not 0.0.0.0; wait until this is done right
+faillimit=0
+IPv4nozero="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} 2> /dev/null | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//' 2> /dev/null)"
+while [ "${IPv4nozero}" = "0.0.0.0" ] || [ "${IPv4nozero}" = "" ]; do
+  IPv4nozero="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} 2> /dev/null | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//' 2> /dev/null)"
+  /usr/bin/sleep 1
+  ### Fail proof
+  if [ "$faillimit" -gt "405" ]; then
+    /opt/rink/run/purgevps ${namespace} ${VerbTLD} ${vuser}
+    e="$?"; [[ "$e" = "0" ]] || exit "$e"
+    /usr/bin/echo "Awe, snap! Could not create ${namespace}.${VerbTLD} properly, likely due to brief backend down time. Try again now or within a few minutes."
+    exit 4
+  fi
+  ((faillimit++))
+done
+
 # Wait for IPv4 to populate (Default until set: 0.0.0.0)
 # firstIPv4PLACEHOLDER="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
 # faillimit=0
@@ -286,25 +302,9 @@ if [ "$e" != "0" ]; then
 fi
 # Process IPs to list for keyscan
 
-# Make sure that the IPv4 is not 0.0.0.0; wait until this is done right
-faillimit=0
-IPv4nozero="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//' 2> /dev/null)"
-while [ "${IPv4nozero}" = "0.0.0.0" ]; do
-  IPv4nozero="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//' 2> /dev/null)"
-  /usr/bin/sleep 1
-  ### Fail proof
-  if [ "$faillimit" -gt "405" ]; then
-    /opt/rink/run/purgevps ${namespace} ${VerbTLD} ${vuser}
-    e="$?"; [[ "$e" = "0" ]] || exit "$e"
-    /usr/bin/echo "Awe, snap! Could not create ${namespace}.${VerbTLD} properly, likely due to brief backend down time. Try again now or within a few minutes."
-    exit 4
-  fi
-  ((faillimit++))
-done
-
 ## Finalize the IP addresses (because they keep changing in spinup)
-IPv4="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
-IPv6Raw="$(/usr/bin/vultr-cli instance ipv6 list ${VultrInstanceID} | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
+IPv4="$(/usr/bin/vultr-cli instance ipv4 list ${VultrInstanceID} 2> /dev/null | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
+IPv6Raw="$(/usr/bin/vultr-cli instance ipv6 list ${VultrInstanceID} 2> /dev/null | /usr/bin/grep main_ip | /usr/bin/sed 's/\s.*$//')"
 IPv6Cmp=$(compress_ipv6 ${IPv6Raw})
 IPv6Exp=$(expand_ipv6 ${IPv6Raw})
 IPv4ARPA=$(/usr/bin/echo ${IPv4} | /usr/bin/sed -r 's/^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$/\4.\3.\2.\1.in-addr.arpa/')
